apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-pv-creator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-utils
  source:
    repoURL: 'https://github.com/Freezl/Sandbox.git'
    path: 01-clusterapp/02-nfs
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nfs-client
  syncPolicy:
    syncOptions:
      - CreateNamespace=true