apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  labels:
    app: monitoring
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: monitoring/charts/vm
    repoURL: 'https://github.com/Freezl/Sandbox.git'
    targetRevision: master
    helm:
      valueFiles:
        - my-values.yaml
  project:  monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
