apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system-utils
  source:
    repoURL: 'https://github.com/Freezl/Sandbox.git'
    path: Base/01-clusterapp/01-base
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy: { }